// <auto-generated />
using System;
using Hx.Sdk.Test.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hx.Sdk.Test.Entity.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20210425085908_InitContext")]
    partial class InitContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Hx.Sdk.Test.Entity.UserInfo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasMaxLength(36);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Creater")
                        .HasColumnType("varchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("CreaterId")
                        .HasColumnType("varchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("LastModifier")
                        .HasColumnType("varchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("LastModifierId")
                        .HasColumnType("varchar(36)")
                        .HasMaxLength(36);

                    b.Property<DateTime?>("LastModifyTime")
                        .HasColumnType("datetime");

                    b.Property<string>("NickName")
                        .HasColumnType("varchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasMaxLength(36);

                    b.HasKey("Id");

                    b.ToTable("UserInfo");

                    b.HasData(
                        new
                        {
                            Id = "f1f69f0d-c546-470a-ba52-8a35b306626e",
                            CreateTime = new DateTime(2021, 4, 25, 16, 59, 8, 313, DateTimeKind.Local).AddTicks(8455),
                            Creater = "SuperAdmin",
                            CreaterId = "SuperAdmin",
                            LastModifier = "",
                            LastModifierId = "",
                            NickName = "宋",
                            PassWord = "123456",
                            UserName = "songtaojie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
